### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [ntankovic/python-bpmn-engine#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by StohanzlMart** [comment]
Hello, I have the same question? What is the license?

**Comment by ntankovic** [comment]
Sorry for late response, will add a MIT license.

**Comment by StohanzlMart** [comment]
> Sorry for late response, will add a MIT license.

Added a pull request with it for you ;)
