### ISSUE TITLE
Just kudos for for project ...

### ISSUE THREAD

**Issue by nitram509** [ntankovic/python-bpmn-engine#6]
Hi @ntankovic ,

I'm the author of https://github.com/nitram509/lib-bpmn-engine and it seems we have the same idea :)
(but just speaking different languages ;) )
Kudo's to you and your project. I left a star for you :)
I would be glad if we could have some implementation-related chat.

Best regards
Martin

PS: not an issue an can be closed.

**Comment by ntankovic** [comment]
Thank you @nitram509 let's connect over LinkedIn.
